<?php

$tableau_appli = array(
    // appli bidon
    "all" => ["port" => 9999],
    // applis normales
    'mellow' =>  ["port" => 5060],
    'oauth' =>  ["port" => 80],
    'filerun' =>  ["port" => 80],
    'duplicati' =>  ["port" => 8200],
    'codif' =>  ["port" => 8443],
    'cloudcmd' =>  ["port" => 8000],
    'bitwarden' =>  ["port" => 80],
    'bookstack' =>  ["port" => 80],
    'sickchill' =>  ["port" => 8081],
    'readarr' =>  ["port" => 8787],
    'ombi' =>  ["port" => 3579],
    'jdownloader' =>  ["port" => 5800],
    'heimdall' =>  ["port" => 80],
    'deluge' =>  ["port" => 8112],
    'firefox' =>  ["port" => 5800],
    'nzbhydra' =>  ["port" => 5076],
    'sabnzbd' =>  ["port" => 8080],
    "radarr" => ["port" => 7878],
    'sonarr' => ["port" => 8989],
    'lidarr' =>  ["port" => 8686],
    "rutorrent" => ["port" => 8080],
    "medusa" => ["port" => 8081],
    'jackett' =>  ["port" => 9117],
    'sensorr' =>  ["port" => 443],
    'emby' =>  ["port" => 8096],
    'bazarr' =>  ["port" => 6767],
    'calibre' =>  ["port" => 8080],
    'calibreweb' =>  ["port" => 8083],
    'nextcloud' =>  ["port" => 80],
    'plex' =>  ["port" => 32400],
    'portainer' =>  ["port" => 9000],    
    'tautulli' =>  ["port" => 8181], 
    'traefik' =>  ["port" => 80], 
    'ubooquity' =>  ["port" => 2202], 
    'watchtower' =>  ["port" => 8080], 
    'kitana' =>  ["port" => 31337], 
    // applis non gérees à partir d'ici
    'monitorr' =>  ["port" => 80],
    'mediawiki' =>  ["port" => 80],
    'mattermost' =>  ["port" => 8080],
    'logarr' =>  ["port" => 80],
    'komga' =>  ["port" => 8080],
    'jitsi' =>  ["port" => 80],
    'dozzle' =>  ["port" => 8080],
    'chevereto' =>  ["port" => 80],
    'autoindex' =>  ["port" => 80],
    'netdata' =>  ["port" => 19999],
    'organizr' =>  ["port" => 80],
    'jellyfin' =>  ["port" => 8096],
    'authelia' =>  ["port" => 8080], 
    'sensorr' =>  ["port" => 8080], 
    'minecraft' =>  ["port" => 8080], 
    'mkvtoolnix' =>  ["port" => 8080], 
    'ntopng' =>  ["port" => 8080], 
    'nowshowing' =>  ["port" => 8080], 
    'openvpn' =>  ["port" => 8080], 
    'piwigo' =>  ["port" => 8080], 
    'pydio' =>  ["port" => 8080], 
    'pyload' =>  ["port" => 8080], 
    'seafile' =>  ["port" => 8080], 
    'subsonic' =>  ["port" => 8080], 
    'synclounge' =>  ["port" => 8080], 
    'syncthing' =>  ["port" => 8080], 
    'varken' =>  ["port" => 8080], 
    'wetty' =>  ["port" => 8080], 
    'wordpress' =>  ["port" => 8080], 
    'gitlab' =>  ["port" => 8080],
    'petio' => ["port" => 7777],
    "overseerr" => ["port" => 5055]

);
