---

- hosts: localhost
  gather_facts: false
  tasks:

    - name: Check if cloudplow.service exists
      stat:
        path: "/etc/systemd/system/cloudplow.service"
      register: cloudplow_service

    - name: Service Tasks
      block:

      - name: Populate Service Facts
        service_facts:

      - name: Get cloudplow service state
        set_fact:
          cloudplow_service_running: "{{ (services['cloudplow.service'] is defined) and (services['cloudplow.service']['state'] == 'running') }}"

      - name: Stop cloudplow service
        become: yes
        systemd:
          name: cloudplow
          state: stopped
        when: cloudplow_service_running

      - name: delete cloudplow.service
        become: yes
        file:
          path: /etc/systemd/system/cloudplow.service
          state: absent

      - name: delete cloudplow folder
        become: yes
        file:
          path: "/home/{{ lookup('env','USER') }}/scripts/cloudplow"
          state: absent

      - name: "create cloudplow state"
        shell: |
          echo "0" > {{ lookup('env','CONFDIR') }}/status/cloudplow

      when: cloudplow_service.stat.exists
