---

- hosts: localhost
  gather_facts: false
  tasks:

    - name: Check if crop.service exists
      stat:
        path: "/etc/systemd/system/crop_upload.service"
      register: crop_upload_service

    - name: Service Tasks
      block:

      - name: Populate Service Facts
        service_facts:

      - name: stopped Systemd Unit
        become: yes
        systemd:
          name: '{{ item }}.service'
          state: stopped
          enabled: no
        with_items:
          - crop_upload
          - crop_sync

      - name: delete crop folder
        become: yes
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - /etc/systemd/system/crop_upload.service
          - /etc/systemd/system/crop_sync.service
          - /etc/systemd/system/crop_upload.timer
          - /etc/systemd/system/crop_sync.timer

      - name: delete crop script
        become: yes
        file:
          path: "/home/{{ lookup('env','USER') }}/scripts/crop"
          state: absent

      - name: "create crop state"
        shell: |
          echo "0" > {{ lookup('env','CONFDIR') }}/status/crop

      when: crop_upload_service.stat.exists
