name: CI
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ master ]

jobs:
  livraison:
    runs-on: ubuntu-latest
    steps:
      - name: Lancement awx
        run: "curl --request POST  --url https://awx.sdewitte.net/api/v2/job_templates/17/launch/  --header 'authorization: Basic ${{ secrets.AUTH_AWX }}'  --cookie __cfduid=d0aa6277fb907532056a58eefe13a568e1598185892"




